spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  mail:
    host: smtp.sina.com
    username: shianywen@sina.com
    password: e57367236460bf3e

  data:
    redis:
      host: localhost
      port: 6379
  #      lettuce:
  #        pool:
  #          max-active: 10
  #          max-idle: 10
  #          min-idle: 0


  jackson:
    default-property-inclusion: non_null # json处理时忽略非空字段

  mvc:
    servlet:
      load-on-startup: 1    #启动就加载servlet
    static-path-pattern: /**
    path match:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  web:
    resources:
      static-locations:
        [ 'classpath:/static/' ]
  main:
    allow-circular-references: true

mybatis-plus:
  configuration:
    #驼峰命名法
    map-underscore-to-camel-case: true
    #打印sql日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
server:
  port: 8080

spring:

  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/journey_of_poet?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

---

server:
  port: 8088

spring:

  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/journey_of_poet?useSSL=false
    username: journey_of_poet
    password: zhengaicha.123

---





